Request
WeiXian042901/fyp_repository pull request #2
Opened 2020-12-08 07:02 UTC by WeiXian042901

2020-12-08 07:21 UTC, jeremiah-ang reviewed
Good and consistent format! Makes the code super easy to read, keep it up! Otherwise, some minor suggestions

2020-12-08 07:21 UTC, jeremiah-ang commented on db.js
> +    return instance ? instance : new DbService();
how about 

```suggestion
    if (!instance) instance = new DbService();
    return instance;
```

2020-12-08 07:21 UTC, jeremiah-ang commented on db.js
> +        FIQ_Points: fiqPoints,
The caller of this function already has this information. Let's do the creation of the response body in app.js instead of database.js.

2020-12-08 07:21 UTC, jeremiah-ang commented on db.js
> +      console.log(error);
Might want to handle some known errors and ultimately return a generic `Unknown Server Error`. 

e.g.

```js
if (is duplicate quiz name error) {
    return { error: "Duplicate Quiz Name", code: "DUPLICATE_QUIZ_NAME" };
} else if (is invalid category Id) {
    return { error: `Invalid Category Id: ${categoryId}", code: "INVALID_CATEGORY_ID" };
} else {
    console.log(error);
    return { error: `Unknown Server Error`, code: "UNKNOWN_SERVER_ERROR" }
}
```

2020-12-08 07:21 UTC, jeremiah-ang commented on db.js
> +      return response === 1 ? true : false;
```suggestion
      return response === 1;
```

2020-12-08 07:21 UTC, jeremiah-ang commented on db.js
> +      return response === 1 ? true : false;
```suggestion
      return response === 1;
```

2020-12-08 07:21 UTC, jeremiah-ang commented on server.js
> +    .then((data) => response.json({ data: data }))
As per my earlier suggestion, the `createQuiz` function should resolve with the `insertId` only. We can form the response here. 

```suggestion
    .then((data) => response.json({
        insertId: data.insertId,
        categoryid: categoryId,
        name: title,
        description: desc,
        FIQ_Points: fiqPoints,
    }))
```

2020-12-08 07:21 UTC, jeremiah-ang commented on server.js
> +});
Lets also implement a 404 and generic error handler.

2020-12-09 12:05 UTC, jeremiah-ang commented on db.js
> +              console.log("error somewhere");
Let's log the error instead.

2020-12-11 08:34 UTC, jeremiah-ang requested changes

2020-12-11 08:34 UTC, jeremiah-ang commented on db.js
> +  }
Rationale: Each function call is resources being used (though it can be small), and by doing this you create a new instance of the string each function call (again, resources being used). As compared to having a single instance that can be reused time and time again.

2020-12-11 08:34 UTC, jeremiah-ang commented on db.js
> +  }
Rationale: This function does not depend on a property of the DbService instance (i.e. it doesn't use `this`)

2020-12-11 08:34 UTC, jeremiah-ang commented on db.js
> +          else reject(err.message);
(personal preference) I typically like to handle the "alternative" flow first, before handling the happy flow. 

i.e. 

```suggestion
          if (err) return reject(result);
          resolve (err.message);
```

Rationale: I like alternative flow to be indented. Whereas happy flow on the "top-level" indentation

2020-12-11 08:34 UTC, jeremiah-ang commented on db.js
> +            console.log(result);
(non-critical, good to know) You might want to console.log first.

2020-12-11 08:34 UTC, jeremiah-ang commented on server.js
> +      quizObject = JSON.parse(JSON.stringify(data));
why the need to stringify and then parse again?

2020-12-11 08:34 UTC, jeremiah-ang commented on server.js
> +  const createQuiz_result = db.createQuiz(
how about `createQuizResult`?

2020-12-11 08:34 UTC, jeremiah-ang commented on server.js
> +      const questionObject = quizObject.quizQuestion;
instead of `questionObject`, how about `questions` or `questionArray`? Since it's not really an object right?

2020-12-11 08:34 UTC, jeremiah-ang commented on server.js
> +      const questionObject = quizObject.quizQuestion;
Similarly, instead of `quizObject.quizQuestion` how about `quizObject.questions` ? (Note: plural for array)

2020-12-11 08:34 UTC, jeremiah-ang commented on server.js
> +        );
Lets do a batch operation, this way, if the quiz have 100 questions, you'd make 100 SQL statements.

2020-12-11 08:34 UTC, jeremiah-ang commented on db.js
> +  async createQuizQuestion(quizId, question) {
(Non-critical, low priority) Let's add a batch operation version too. 

```js

async createQuizQuestions(quizId, questions) {
    // try, and return new Promise omitted to be concise
    const query = `
        INSERT INTO quiz_question (quizId, questionObject) 
        VALUES ${questions.map(() => '(?, ?)')}
    `;  // e.g. INSERT INTO ... VALUES (?, ?), (?, ?), ..., (?, ?) 
    const params = [];
    questions.forEach((question) => params.push(quizId, question));
    connection.query(query, params, (err, result) => {...});
}
```

2020-12-11 08:34 UTC, jeremiah-ang commented on server.js
> +      response.json({ data: data });
What if we update the quiz successfully but had some error updating the questions?

2020-12-11 09:00 UTC, WeiXian042901 commented on server.js
> +      const questionObject = quizObject.quizQuestion;
it is a object

2020-12-11 09:08 UTC, WeiXian042901 commented on server.js
> +      response.json({ data: data });
already caught the error back in db.js

2020-12-11 09:15 UTC, WeiXian042901 commented on server.js
> +      quizObject = JSON.parse(JSON.stringify(data));
data is RowDataPacket, I have to make it a json object first to access the things in it LOL.
The rest is self explanatory :)

2020-12-11 09:18 UTC, WeiXian042901 commented on db.js
> +  }
Will do after merging with main branch

2020-12-11 09:18 UTC, WeiXian042901 commented on server.js
> +        );
will look into it

2020-12-11 10:31 UTC, merged